---
- name: This is a recipe for how to cook with release-bot
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    ansible_bender:
      base_image: FROM registry.fedoraproject.org/fedora:30
      #base_image: fedora:29
      target_image:
        name: docker.io/usercont/packit-service
        environment:
          FLASK_APP: packit.service.web_hook
        cmd: flask-3 run -h 0.0.0.0
      working_container:
        volumes:
        - '{{ playbook_dir }}:/src:Z'
  tasks:
  - name: Create /usr/share/packit directory
    file:
      state: directory
      path: '{{ item }}'
    with_items:
    - /usr/share/packit
    - /packit-ssh  # this is where we put ssh creds
    - /sandcastle  # working dir for the upstream git which is mapped to the sandbox pod
  - name: Create some home dirs
    file:
      state: directory
      path: '{{ home_path }}/{{ item }}'
      mode: 0700
    with_items:
    - .ssh
    - .config
  - name: Create /secrets
    file:
      state: directory
      path: /secrets
      mode: 0777
  - name: Copy gitconfig
    copy:
      src: gitconfig
      dest: '{{ home_path }}/.gitconfig'
  - name: stat /src
    stat:
      path: /src
    tags:
    - no-cache
    register: src_path
  - name: Let's make sure /src is present
    assert:
      that:
      - 'src_path.stat.isdir'
  - name: Copy run.sh
    copy:
      src: run.sh
      dest: /usr/bin/run.sh
      mode: 0777
  - name: Install ogr from git master
    pip:
      name: git+https://github.com/packit-service/ogr.git
      executable: pip3
  - name: Install release-bot from /src
    pip:
      name: /src
      executable: pip3
  - name: Clean all the cache files (especially pip)
    shell: rm -rf ~/.cache/*